### ISSUE TITLE
Problem with SEP and Swuft-UVOT frames

### ISSUE THREAD

**Issue by stefanocovino** [sep-developers/sep#15]
HI all,

I am reporting a bug when running sep with Swift-UVOT FITS files. 

This is the operations I do:

from astropy.io.fits import get data
import sep

dt = getdata('sw00033001022um2_sk_1.fits')
data = dt.astype(numpy.float32)
bkg = sep.Background(data)
bkg.subfrom(data)
objs = sep.extract(data, 5. \* bkg.globalrms)
## and this is what I get:

Exception                                 Traceback (most recent call last)
<ipython-input-22-5d6d97afd6c4> in <module>()
----> 1 objs = sep.extract(data, 5. \* bkg.globalrms)

/Users/covino/.python-eggs/sep-0.1.0-py2.7-macosx-10.5-x86_64.egg-tmp/sep.so in sep.extract (sep.c:4697)()

/Users/covino/.python-eggs/sep-0.1.0-py2.7-macosx-10.5-x86_64.egg-tmp/sep.so in sep._assert_ok (sep.c:2828)()

Exception: SEP internal error

Any idea?

I can send the FITS file if useful.

Thanks,
   Stefano

**Comment by RobinThomas95** [comment]
Hi everyone, I'm working with UVIT FITS files. I tried using SEP for background subtraction. After completion of the same, I save the background-subtracted image as a new FITS file with header same as the original file. On opening this newly saved file in SAODS9, I find white patches near areas that have bright knots. I'm attaching the original image and the background-subtracted
 image.

![what on earth](https://user-images.githubusercontent.com/49048610/110287951-4bd34800-800d-11eb-9a16-e9c323036d75.jpeg)
![okIMAGE](https://user-images.githubusercontent.com/49048610/110288062-73c2ab80-800d-11eb-9187-2f5931b03919.jpg)
